targets:
  $default:
    builders:
      bdd_flutter|bdd_test_builder:
        options:
          # generate_widget_tests:
          # enable_reporter: true
          ignore_features:
            - "test/calculator/calculator.feature"
