name: bdd_flutter
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/samderlust/bdd_flutter

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  build: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.0
  test: ^1.20.0
