name: bdd_flutter
description: A Flutter package for Behavior-Driven Development (BDD) testing.
version: 0.0.1
homepage: https://github.com/samderlust/bdd_flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

topics:
  - bdd
  - test
  - widgettest
  - gherkin

dependencies:
  yaml: ^3.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.0
