name: bdd_flutter
description: "A powerful Flutter package that simplifies Behavior Driven Development (BDD) by automatically generating test files from Gherkin feature files"
version: 0.2.0
homepage: https://github.com/samderlust/bdd_flutter

environment:
  sdk: ^3.1.0
  flutter: ">=3.1.0"

dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.0.0
  build: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.3.0
  test: ^1.20.0

executables:
  bdd: bdd
